### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by BrekiTomasson** [steven2358/reveye#6]
Has this extension been abandoned? I see the question regarding the URL change for Yandex hasn't been addressed, for example, despite it being a very simple change (replacing `img_url` in the URI pattern with just `url`). Just wondering if I should fork it and fix it myself or if I can expect a fix down the line.

**Comment by steven2358** [comment]
The fix has arrived!

The extension is not abandoned btw. But support is slow. The culprit is 2020.
