### ISSUE TITLE
Search results tab opens at the end of tabs row.

### ISSUE THREAD

**Issue by Scott274** [steven2358/reveye#7]
Very good extension but gave it 1 star less because the search results open in a tab at the end of the Chrome tabs row. This is inconvenient if you have lots of tabs open and if you have tabs overflow in a Chrome window, the search results just disappears in the overflow end. Search results should open in a tab right besides the searched image tab.

**Comment by steven2358** [comment]
Valid point. Will consider it next time I work on this project.
