### ISSUE TITLE
Register for BAT tips to receive thanks from users

### ISSUE THREAD

**Issue by BizarrePenguin** [steven2358/reveye#9]
If you are not @steven2358, please ignore this issue!

The extension is a small but really helpful extension, thank you!
This is why I wanted to leave a tip in form of BAT (basic attention tokens) for you @steven2358. Unfortunetely you are not verified to receive them yet. See this page for more information: [https://creators.brave.com/](https://creators.brave.com/)
I apologize for misusing the issues tab for contacting you, but I could not find another way.
Since you seem to be involved in the crypto space I wondered if it might interest you to register so you can receive tips from thankful users of your projects.

Please feel free to delete this issue as soon as you read it so it does not clog up your issues tab.
Please forgive me to contact you via this way.

Disclaimer: I am not from Brave, nor payed to advert for them, nor am I a bot. I am just a regular user that likes your extension and wanted to give you a (too be fair small) tip in form of BAT.

**Comment by steven2358** [comment]
Good suggestion! I registered for BAT tips and have added a small description for donations to the readme. Some minor improvements are planned, and donations will certainly help the development.
